import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function RoverAnimationControls({ waypointsGeoJson, terrainData, animation, }) {
    const hasWaypoints = waypointsGeoJson &&
        waypointsGeoJson.features &&
        waypointsGeoJson.features.length > 0;
    if (!hasWaypoints) {
        return (_jsx("div", { className: "bg-gray-800 rounded-lg p-4", children: _jsx("p", { className: "text-gray-400 text-sm", children: "No waypoints available. Generate a route to enable rover animation." }) }));
    }
    const { state, play, pause, reset, setSpeed, seek } = animation;
    return (_jsxs("div", { className: "bg-gray-800 rounded-lg p-4 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-lg font-semibold text-white", children: "Rover Animation" }), _jsx("button", { onClick: reset, className: "px-3 py-1 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-md transition-colors", children: "Reset" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { onClick: state.isPlaying ? pause : play, className: `px-6 py-2 rounded-md font-medium transition-colors ${state.isPlaying
                            ? 'bg-yellow-600 hover:bg-yellow-700 text-white'
                            : 'bg-green-600 hover:bg-green-700 text-white'}`, children: state.isPlaying ? '⏸ Pause' : '▶ Play' }), _jsxs("div", { className: "flex-1", children: [_jsxs("label", { className: "block text-sm font-medium text-gray-300 mb-1", children: ["Speed: ", state.speed.toFixed(1), "x"] }), _jsx("input", { type: "range", min: "0.1", max: "5", step: "0.1", value: state.speed, onChange: (e) => setSpeed(parseFloat(e.target.value)), className: "w-full" })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "block text-sm font-medium text-gray-300 mb-1", children: ["Progress: ", Math.round(state.progress * 100), "%"] }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "range", min: "0", max: "1", step: "0.01", value: state.progress, onChange: (e) => seek(parseFloat(e.target.value)), className: "w-full" }), _jsx("div", { className: "absolute top-0 left-0 h-1 bg-blue-500 rounded", style: { width: `${state.progress * 100}%` } })] })] }), state.currentPosition && (_jsxs("div", { className: "grid grid-cols-2 gap-4 pt-2 border-t border-gray-700", children: [_jsxs("div", { children: [_jsx("div", { className: "text-xs text-gray-400", children: "Position" }), _jsxs("div", { className: "text-sm text-white", children: ["Lat: ", state.currentPosition.lat.toFixed(6)] }), _jsxs("div", { className: "text-sm text-white", children: ["Lon: ", state.currentPosition.lon.toFixed(6)] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-xs text-gray-400", children: "Status" }), _jsxs("div", { className: "text-sm text-white", children: ["Elevation: ", Math.round(state.currentPosition.elevation), " m"] }), _jsxs("div", { className: "text-sm text-white", children: ["Heading: ", Math.round(state.currentPosition.heading), "\u00B0"] })] }), _jsxs("div", { className: "col-span-2", children: [_jsx("div", { className: "text-xs text-gray-400", children: "Waypoint Progress" }), _jsxs("div", { className: "text-sm text-white", children: ["Segment ", state.currentPosition.waypointIndex + 1, " (", Math.round(state.currentPosition.progress * 100), "% complete)"] })] })] })), !state.currentPosition && (_jsx("div", { className: "text-sm text-gray-400 text-center py-2", children: "Click Play to start animation" }))] }));
}
