import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function SiteScoresList({ sites, selectedSite, onSelectSite }) {
    const [expandedSite, setExpandedSite] = useState(null);
    return (_jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "font-semibold mb-3", children: "Site Rankings" }), _jsx("div", { className: "space-y-2 max-h-96 overflow-y-auto", children: sites.map((site) => (_jsxs("div", { className: `p-3 rounded border-2 cursor-pointer transition-colors ${selectedSite === site.site_id
                        ? 'border-blue-500 bg-blue-900/30'
                        : 'border-gray-700 bg-gray-700/50 hover:bg-gray-700'}`, onClick: () => onSelectSite(site.site_id), children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsxs("div", { children: [_jsxs("div", { className: "font-semibold text-sm", children: ["Rank #", site.rank, " - Site ", site.site_id] }), _jsxs("div", { className: "text-xs text-gray-400 mt-1", children: ["Score: ", (site.total_score * 100).toFixed(1), "%"] })] }), _jsx("button", { onClick: (e) => {
                                        e.stopPropagation();
                                        setExpandedSite(expandedSite === site.site_id ? null : site.site_id);
                                    }, className: "text-gray-400 hover:text-gray-300 text-xs", children: expandedSite === site.site_id ? '▼' : '▶' })] }), _jsx("div", { className: "text-xs text-gray-300 mb-2", children: site.explanation }), expandedSite === site.site_id && (_jsxs("div", { className: "mt-2 pt-2 border-t border-gray-700 text-xs", children: [_jsx("div", { className: "text-gray-400 mb-1", children: "Component Breakdown:" }), _jsx("div", { className: "space-y-1", children: Object.entries(site.components).map(([key, value]) => (_jsxs("div", { className: "flex justify-between", children: [_jsxs("span", { className: "text-gray-400 capitalize", children: [key.replace('_', ' '), ":"] }), _jsx("span", { className: "text-gray-300", children: typeof value === 'number' ? value.toFixed(2) : value })] }, key))) }), _jsxs("div", { className: "mt-2 pt-2 border-t border-gray-700", children: [_jsxs("div", { className: "text-gray-400", children: ["Area: ", site.area_km2.toFixed(2), " km\u00B2"] }), _jsxs("div", { className: "text-gray-400", children: ["Location: ", site.centroid_lat.toFixed(4), "\u00B0, ", site.centroid_lon.toFixed(4), "\u00B0"] })] })] }))] }, site.site_id))) })] }));
}
